config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/', to: 'reports#new', as: 'root'
  get 'reports/:report_id/search_results/:id/page_cache', to: 'search_results#page_cache', as: 'page_cache'
  resources :reports, only: [:index, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/report.rb
class Report < ApplicationRecord
  has_many :search_results
  belongs_to :user

  validates :keywords, presence: true

  after_create :generate_search_results

  def generate_search_results
    self.keywords.each do |keyword|
      SearchResult.create!(keyword: keyword, report: self)
    end
  end
end

app/models/search_result.rb
class SearchResult < ApplicationRecord
    enum status: [:pending, :ready]

    belongs_to :report
    
    validates :keyword, :report_id, presence: true
    
    after_create_commit :scrape_result

    def scrape_result
        ResultScrapeJob.perform_later(self.id, self.keyword)
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # :registerable, :recoverable, :validatable
  devise :database_authenticatable, :rememberable

  has_many :reports

  def create_report!(keywords)
    reports.create!({ keywords: keywords })
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound do
    render file: "public/404.html"
  end
end

app/controllers/concerns/localization.rb
module Localization
  extend ActiveSupport::Concern

  included do
    before_action :set_locale

    protected

    def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
    end
  end
end

app/controllers/reports_controller.rb
require "csv"

class ReportsController < ApplicationController
  before_action :authenticate_user!

  def index
    @reports = current_user.reports
  end

  def new
    @report = current_user.reports.new()
  end

  def create
    if file = params[:file]
      keywords = keywords_from_csv(file.path)
      report = current_user.create_report!(keywords)
      redirect_to(report)
    else
      render file: "public/422.html"
    end
  end

  def show
    @report = current_user.reports.find(params[:id])
  end

  private
  def keywords_from_csv(file_path)
    csv = CSV.parse(csv_text(file_path), :headers => false)
    keywords = csv.map { |keyword| keyword[0] }
  end

  def csv_text(file_path)
    File.read(file_path)
  end

end

app/controllers/search_results_controller.rb
class SearchResultsController < ApplicationController
  before_action :authenticate_user!

  def page_cache
    report = current_user.reports.find(params[:report_id])
    @search_result = report.search_results.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_menu_class(path)
    'active' if current_page?(path)
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/search_results_helper.rb
module SearchResultsHelper
end

app/views/layouts/_menus.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "Report Generator", root_path, class: "nav-link #{active_menu_class(root_path)}" %>
      </li>
      <li class="nav-item">
        <%= link_to "Report History", reports_path, class: "nav-link  #{active_menu_class(reports_path)}" %>
      </li>
      <li class="nav-item">
        <span class="navbar-text text-info">You are Logged in as <%= current_user.email %></span>
      </li>
      <li class="nav-item pull-right">
        <%= link_to "Logout", destroy_user_session_path, class: "nav-link", method: :delete %>  
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchResultChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render 'layouts/menus' %>
    <% end %>
    <div class="container p-3 center">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/reports/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h2>
        Report History
      </h2>
      <ul class="list-group">
        <% @reports.each do |report| %>
          <li class="list-group-item">
            <%= link_to report do %>
              Report#<%= report.id %> (<%= report.keywords.size %> keywords) 
              <small><%= time_ago_in_words(report.created_at) %> ago</small>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/reports/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <%= form_tag({action: :create}, multipart: true) do %>
        <div class="form-group">
          <%= label_tag "Upload file with keywords (max keywords is 100)" %><br>
          <small>You can use <%= link_to 'this sample file', root_url+"sample_file.csv" %></small>
          <%= file_field_tag :file, {class: "form-control", accept: '.csv'} %>
        </div>
        <%= submit_tag "Generate Report", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/reports/show.html.erb
<div class="container padding">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      Report#<%= @report.id %> contains <%= @report.keywords.size %> keywords <br>
      generated <%= time_ago_in_words(@report.created_at) %> ago
      <% @report.search_results.each do |search_result| %>
        <div class="card">
          <div class="card-body">
            Keyword: <%= search_result.keyword %><br>
            <% if search_result.ready? %>
              Result Stats: <%= search_result.result_stats %><br>
              No. of results: <%= search_result.no_of_results %><br>
              No. of links: <%= search_result.no_of_links %><br>
              No. of AdWords: <%= search_result.no_of_adwords %><br>
              Page Cache: <%= link_to "Result#{search_result.id}", page_cache_path(report_id: @report.id, id: search_result.id) %><br>
            <% else %>
              Processing...
            <% end %>
          </div>
        </div>
      <% end %>
    <div>
  </div>
</div>

app/views/search_results/page_cache.html.erb
<%= raw(@search_result.page_cache) %>